# MongoDB
quarkus.mongodb.connection-string=mongodb+srv://bookaero:bookaero123@bookareo.sa6cmbs.mongodb.net/?retryWrites=true&w=majority&appName=bookareo
quarkus.mongodb.database=bookaero

# Keycloak OIDC
quarkus.oidc.auth-server-url=http://localhost:9091/realms/bookaero
quarkus.oidc.client-id=bookaero-client
quarkus.oidc.application-type=service
quarkus.oidc.token.audience=account

# Public Endpoint
quarkus.http.auth.permission.public.paths=/user/register
quarkus.http.auth.permission.public.policy=permit

# Secure All Others
quarkus.http.auth.permission.secured.paths=/*
quarkus.http.auth.permission.secured.policy=authenticated
